# Generated by Django 5.1 on 2024-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Herbal Medicine', 'Herbal Medicine'), ('Ayurvedic Consultation', 'Ayurvedic Consultation'), ('Holistic Therapies', 'Holistic Therapies')], max_length=100)),
                ('doctor', models.CharField(choices=[('Dr. A. Sharma', 'Dr. A. Sharma'), ('Dr. B. Mehta', 'Dr. B. Mehta'), ('Dr. C. Patel', 'Dr. C. Patel')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
        ),
    ]
