# Generated by Django 5.1 on 2024-08-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('precautions', models.TextField()),
                ('what_to_eat', models.TextField()),
                ('daily_exercise', models.TextField()),
                ('exercise_instructions', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.ImageField(upload_to='media/Registration/')),
                ('treatment', models.TextField()),
                ('medicine', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Precaution.disease')),
            ],
        ),
    ]
