# Generated by Django 5.1 on 2024-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Precaution', '0002_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='media/Registration/'),
        ),
    ]
