# Generated by Django 5.1 on 2024-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Precaution', '0003_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/Registration/'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
