# Generated by Django 5.1 on 2024-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('Ayurveda', 'Ayurveda'), ('Herbal Medicine', 'Herbal Medicine'), ('Naturopathy', 'Naturopathy')], max_length=50)),
                ('disease', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
    ]
