# Generated by Django 5.1 on 2024-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/aru2.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
